### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by SirBurton** [LuckySalmon/JackofAllTrades#4]
`Traceback (most recent call last):
  File "D:\Documents\GitHub\JackofAllTrades\JackofAllTrades.py", line 1, in <module>
    import characters
  File "D:\Documents\GitHub\JackofAllTrades\characters.py", line 6, in <module>
    from panda3d.bullet import BulletConeTwistConstraint, BulletGenericConstraint, BulletHingeConstraint
ImportError: cannot import name 'BulletConeTwistConstraint' from 'panda3d.bullet' (unknown location)`

This is from a freshly cloned copy, running on python 3.9.6 on Windows 11

**Comment by WMOkiishi** [comment]
Yes... the project requires Panda3D, which is available through PyPI. Is there a standard way of noting this? Or a way to automatically install it?

**Comment by SirBurton** [comment]
Yes. 
Make a file called requirements.txt
Examples here:  [https://pip.pypa.io/en/stable/cli/pip_install/#requirements-file-format](https://pip.pypa.io/en/stable/cli/pip_install/#requirements-file-format)

**Comment by WMOkiishi** [comment]
Ok; I think I've done that correctly. Does it work now?

**Comment by SirBurton** [comment]
Yes.
You may want to write instructions for the installation that tells the user to install the requirements.
`pip install -r requirements.txt`

Or, you can with your code look to see if the module exists, and if not, install it for them.  
It is polite to always ask before installing things on someone's computer.

But now with this file at least, the gitHub savvy user will at least know what they need to install to make this work.
